### ISSUE TITLE
Have you gotten this to work on Travis or CircleCI?

### ISSUE THREAD

**Issue by jcoyne** [drivy/rails-headless-capybara#2]
I've tried on Travis and I'm  getting:
```
     Selenium::WebDriver::Error::WebDriverError:

        Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

My `.travis.yml` has 
```yaml
before_install: 
   - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/chromedriver/
    - export CHROME_BIN=chromium-browser       
```

**Comment by TimPetricola** [comment]
Hey @jcoyne, I didn't try using it on Travis but according to the doc you should be able to set it up with the following config:

```yml
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
```

You can have a lookg at [their doc](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode) for more info :)
